[package]
name = "deepstream-sys"
version = "0.1.0"
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.0"
glib-sys = "0.14.0"
gst-sys = { version = "0.17.2", package = "gstreamer-sys" }
